<a href="https://colab.research.google.com/github/Elvwhu/python-numpy-pandas/blob/main/clase_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **Indexación**
Forma de acceder a los elementos de un array por medio de su índice.

📢 Los indices empiezan a partir del 0 que representa el primer elemento del array.

In [13]:
import numpy as np
array = np.random.randint(5, 30, 20)
print(array)

print("Elemento en la posición 5:", array[4])
print("Elemento en la primer posición:", array[0])
print("Elemento en la última posición", array[-1])
print("Elemento en la ante última posición", array[-2])

[19 16 21 18 26 11 16  8 12 17  7 23  6 26 25 17 12 20 24  7]
Elemento en la posición 5: 26
Elemento en la primer posición: 19
Elemento en la última posición 7
Elemento en la ante última posición 24


##Indexación booleana

Forma de obtener datos a partir de una condición.

📢 Todos los elementos que cumplan con la condición serán “devueltos”.

In [4]:
bool_index = array > 15
print("Array booleano:", bool_index)
print("Elementos mayortes a 15:", array[bool_index])
print("Elementos entre 15 y 20:", array[(array >= 15 ) & (array <= 20)])

Array booleano: [ True False  True False False  True False False False  True  True  True
  True  True  True  True  True False  True  True]
Elementos mayortes a 15: [18 19 21 20 22 28 27 25 17 20 24 18 18]
Elementos entre 15 y 20: [18 19 15 20 17 20 15 18 18]


##Indexación por listas

Permite obtener multiples elementos de un array con una lista de indices.

📢 Al mandarle indices “desordenados” el array resultante obtiene los elementos en el orden en que se pasó el índice centro de la lista.

In [14]:
index_list = [3,8,5,0]
print("Elementos en las posiciones 3,8,5 y 0:", array[index_list])
print("Elementos en las posiciones -1, 2,3 y 5:", array[[-1,2,3, 5]])





Elementos en las posiciones 3,8,5 y 0: [18 12 11 19]
Elementos en las posiciones -1, 2,3 y 5: [ 7 21 18 11]
Elemento de la fila 2, columna 2: 6
Elementos de las fila 1 y 2, columna 2: [20  6]
Elementos en la fila 1 , columna 2, y fila 3, columna 2: [6 6]
Elementos mayores a 18: [27 29 26 20 20 25 29 29 20 23 21]


##Indexación de arrays multidimensionales

📢 ara acceder a un elemento de un array bidimensional, le indicamos 2 indice **[indice_fila, indice_columna]**

In [17]:
matrix = np.random.randint(5, 30, (5,5))
print (matrix)
print("Elemento de la fila 2, columna 2:", matrix[2,2]) # Elemento especifio
print("Elementos de las fila 1 y 2, columna 2:", matrix[[1,2],2]) # Indexaciónb por lista (1)
print("Elementos en la fila 1 , columna 2, y fila 3, columna 2:", matrix[[1,2],[3,2]]) # Indexaciónb por lista (2)
print("Elementos mayores a 18:", matrix[matrix > 18]) # Indexación booleana

[[15 22 18 26 29]
 [24 22 29 27 25]
 [ 5  5 21 24 15]
 [26 14 12 14 10]
 [ 8 21 24 12 19]]
Elemento de la fila 2, columna 2: 21
Elementos de las fila 1 y 2, columna 2: [29 21]
Elementos en la fila 1 , columna 2, y fila 3, columna 2: [27 21]
Elementos mayores a 18: [22 26 29 24 22 29 27 25 21 24 26 21 24 19]
