<a href="https://colab.research.google.com/github/Elvwhu/python-numpy-pandas/blob/main/clase_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Transformación de Arrays
Transpuesta
La transpuesta de una matriz en NumPy se puede obtener utilizando el método .T. Este método intercambia las filas y columnas de la matriz original. Por ejemplo, si tienes una matriz A, su transpuesta se obtiene con A.T.

In [4]:
import numpy as np
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

#Matriz normal
print(matrix,"\n")

#Matriz invertida o transpuesta
transposed_matrix = matrix.T
print(transposed_matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


##Reshape
El método reshape de NumPy permite cambiar la forma de un array sin alterar sus datos. Por ejemplo, si tienes un array B de forma (2, 3), puedes cambiarlo a una forma (3, 2) utilizando .reshape(3, 2).

In [18]:
array = np.arange(1,13)
reshaped_array = array.reshape (3,4)

print ("Array original:", array)
print ("\n Array con Reshape:\n", reshaped_array)

Array original: [ 1  2  3  4  5  6  7  8  9 10 11 12]

 Array con Reshape:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


##Reverse

In [21]:
array = np.arange(1,16)
reversed_array = array[::-1]
print ("Array origninal:", array)
print ("\nArray reverso:", reversed_array)

Array origninal: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

Array reverso: [15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


##Flattening
El método flatten de NumPy convierte un array multidimensional en un array unidimensional. Esto es útil cuando necesitas trabajar con datos en una forma lineal. Por ejemplo, si tienes un array D de forma (2, 3), puedes aplanarlo utilizando .flatten().


In [22]:
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

flattened_matrix = matrix.flatten()
print ("Matriz original:\n", matrix)
print ("\nMatriz con Flattening:", flattened_matrix)

Matriz original:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matriz con Flattening: [ 1  2  3  4  5  6  7  8  9 10 11 12]
